[package]
name = "zk-proof-server"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
log = "0.4"
env_logger = "0.10"
num-bigint = "0.4"
hex = "0.4"
poseidon-rs = "0.0.10"
ff_ce = "0.11"
